<?php
/**
* Implements hook_entity_info_alter().
*/

function fc_form_overrides_theme($existing, $type, $theme, $path){
  return array(
    'user_register' => array(
      'render element' => 'form',
      'template' => 'templates/user-register',
    ),
  );
}


function fc_form_overrides_form_alter(&$form, $form_state, $form_id){
	unset($form['account']['mail']['#description']);
	unset($form['account']['pass']['#description']);
	$form['account']['mail']['#title'] = t('Email');
	$form['account']['name']['#title'] = t('Custom URL');
	
	switch ($form_id){
		case 'apachesolr_search_custom_page_search_form':
			$form['#attributes']['class'][] = 'clearfix';
			$form['basic']['keys']['#title'] = t('Search: ');
			$form['basic']['submit']['#type'] = 'image_button';
			$form['basic']['submit']['#src'] = '/fc/' . path_to_theme() . '/images/FC_search_btn.png';	
			//dsm($form);		
		break;
		
		case 'search_form':
			$form['#attributes']['class'][] = 'clearfix';
			$form['basic']['keys']['#title'] = t('Search: ');
			$form['basic']['submit']['#type'] = 'image_button';
			$form['basic']['submit']['#src'] = '/fc/' . path_to_theme() . '/images/FC_search_btn.png';
			//dsm($form);
		break;
		
		case 'search_block_form':
			//dpm($form);
			$form['#attributes']['class'][] = 'clearfix';
			//$form['basic']['keys']['#title'] = t('Search: ');
			$form['actions']['submit']['#type'] = 'image_button';
			$form['actions']['submit']['#src'] = '/fc/' . path_to_theme() . '/images/FC_search_btn.png';
		break;
		
		case 'comment_node_article_form':
		case 'comment_node_news_form':
		case 'comment_node_need_form':
		case 'comment_node_project_form':
		case 'comment_node_pictures_form':
		case 'comment_node_videos_form':
		case 'comment_node_event_form':
			$form['actions']['submit']['#value'] = t('Post Comment');
			$form['comment_body']['#after_build'][] = 'fc_form_overrides_customize_comment_form';			
		break;
		
	}
	
}

function fc_form_overrides_customize_comment_form(&$form){
	$form[LANGUAGE_NONE][0]['format']['#access'] = FALSE; 
	return $form;
}

function fc_form_overrides_form_profile2_form_alter(&$form, &$form_state) {
	if($form['profile_user']){
	
		
		
	}elseif($form['profile_charity']){
	
		
	}
}

function fc_form_overrides_form_user_register_form_alter(&$form, $form_state){
	$form['#theme'] = 'user_register';
}


